// ElemeModule — 饿了么外卖
const ElemeModule = (() => {
  const KF='eleme-foods',KO='eleme-orders';
  let _f=[],_o=[],_e=null;
  function _u(){return'EM'+Date.now().toString(36)+Math.random().toString(36).slice(2,6)}
  function _fm(n){return'¥'+Number(n).toFixed(2)}
  async function _L(){try{_f=await DB.settings.get(KF)||[]}catch(e){_f=[]};try{_o=await DB.settings.get(KO)||[]}catch(e){_o=[]}}
  async function _sF(){await DB.settings.set(KF,_f)}
  async function _sO(){await DB.settings.set(KO,_o)}
  async function _AI(prompt,temp){
    let api=null;try{api=await ApiModule.getSecondaryApi()}catch(e){api=await DB.api.getActive().catch(function(){return null})}
    if(!api)return null;
    var fp=prompt;try{var es=await DB.worldInfo.getAll();if(es&&es.length){var fl=es.filter(function(e){return e.scope&&Array.isArray(e.scope)&&e.scope.includes('eleme')});if(fl.length)fp+='\n【世界书参考】'+fl.map(function(e){return e.title+'：'+(e.content||'').slice(0,80)}).join(' | ').slice(0,500)}}catch(e){}
    try{return await ApiHelper.chatCompletion(api,[{role:'user',content:fp}])}catch(e){console.error('[Eleme]',e);return null}
  }
  async function _GI(prompt,fid){var sp=(prompt||'food').slice(0,200);var seed=Math.floor(Math.random()*100000);var url='https://image.pollinations.ai/prompt/'+encodeURIComponent(sp+', food photography')+'?width=512&height=512&seed='+seed+'&model=flux&nologo=true';var img=document.getElementById('em-img-'+fid);if(img){img.src=url;img.onerror=function(){img.style.display='none';var fb=img.nextElementSibling;if(fb)fb.style.display='flex'};img.onload=async function(){var p=_f.find(function(x){return x.id===fid});if(p){p.imageUrl=url;await _sF()}}}}
  async function aiSearch(kw){var k=(kw||'').trim();if(!k){aiGen();return}var prompt='你是外卖App的搜索引擎。根据"'+k+'"创作5-8款外卖美食JSON数组。每款: name, price(数字), restaurant(店铺), imagePrompt(英文美食图提示词, appetizing food photography)。严格只返回JSON数组。';var resp=await _AI(prompt,0.8);if(!resp){_T('AI调用失败');return}try{var cleaned=resp.replace(/```json|```/g,'').trim();var arr=JSON.parse(cleaned.substring(cleaned.indexOf('['),cleaned.lastIndexOf(']')+1));if(Array.isArray(arr)&&arr.length>0){var items=arr.map(function(p){return{id:_u(),name:p.name,price:Number(p.price)||30,restaurant:p.restaurant||'私房小厨',imagePrompt:p.imagePrompt||'',imageUrl:''}});_f.push.apply(_f,items);_sF();_r();_T('找到'+items.length+'款美食');items.forEach(function(p){if(!p.imageUrl)_GI(p.imagePrompt||p.name,p.id)})}}catch(e){_T('AI返回格式错误')}}
  async function aiGen(){var prompt='你是外卖App的策划师。随机创作5-8款有趣多样的美食JSON数组。每款: name, price(数字), restaurant(店铺), imagePrompt(英文美食产品图, appetizing food photography)。严格只返回JSON数组。';var resp=await _AI(prompt,1.0);if(!resp){_T('AI调用失败');return}try{var cleaned=resp.replace(/```json|```/g,'').trim();var arr=JSON.parse(cleaned.substring(cleaned.indexOf('['),cleaned.lastIndexOf(']')+1));if(Array.isArray(arr)&&arr.length>0){var items=arr.map(function(p){return{id:_u(),name:p.name,price:Number(p.price)||30,restaurant:p.restaurant||'私房小厨',imagePrompt:p.imagePrompt||'',imageUrl:''}});_f.push.apply(_f,items);_sF();_r();_T('生成了'+items.length+'款美食');items.forEach(function(p){if(!p.imageUrl)_GI(p.imagePrompt||p.name,p.id)})}}catch(e){_T('AI返回格式错误')}}
  function _r(){var g=document.getElementById('em-food-grid');if(!g)return;if(_f.length===0){g.innerHTML='<div class="em-empty">还没有美食哦<br>点右上角 + 或 ✨ 来发现美味吧！</div>'}else{g.innerHTML=_f.map(function(p){var ih=p.imageUrl?'<img src="'+p.imageUrl+'" class="em-card-img" id="em-img-'+p.id+'" onerror="this.style.display=\'none\';this.nextElementSibling.style.display=\'flex\'"><div class="em-card-emoji-fb" style="display:none">🍽</div>':'<div class="em-card-emoji">🍽</div>';return'<div class="em-card"><div class="em-card-img-wrap" onclick="ElemeModule._oD(\''+p.id+'\')">'+ih+'</div><div class="em-card-info" onclick="ElemeModule._oD(\''+p.id+'\')"><div class="em-card-name">'+p.name+'</div><div class="em-card-shop">'+(p.restaurant||'')+'</div><div class="em-card-price">'+_fm(p.price)+'</div></div><button class="em-card-btn" onclick="event.stopPropagation();ElemeModule._oFC(\''+p.id+'\')">点单</button></div>'}).join('')}_rO()}
  function _rO(){var el=document.getElementById('em-orders-list'),sec=document.getElementById('em-orders-section');if(!el)return;if(_o.length===0){if(sec)sec.style.display='none';return}if(sec)sec.style.display='block';el.innerHTML=_o.slice(0,10).map(function(o){return'<div class="em-order-card"><div style="display:flex;justify-content:space-between"><b>'+(o.foodName||'美食')+'</b><span style="color:#ff6b35;font-weight:800">'+_fm(o.price)+'</span></div><div style="font-size:0.6rem;color:#999;margin:2px 0">'+(o.restaurant||'')+' · '+new Date(o.time).toLocaleString('zh-CN')+'</div><div style="font-size:0.65rem;color:#ff6b35;font-weight:600">为 <b>'+(o.charName||'角色')+'</b> 点单'+(o.remark?' · 备注: '+o.remark:'')+'</div></div>'}).join('')}
  async function _oFC(fid){var food=_f.find(function(x){return x.id===fid});if(!food)return;var chars=await DB.characters.getAll().catch(function(){return[]});if(!chars.length){_T('还没有角色');return}var pk=document.getElementById('em-char-picker');pk.innerHTML='<div style="color:#fff;text-align:center;margin-bottom:12px;font-weight:700;font-size:0.9rem">为谁点「'+food.name+'」？<br><span style="font-size:0.7rem;font-weight:400;opacity:0.8">'+_fm(food.price)+'</span></div><div style="display:flex;flex-wrap:wrap;gap:10px;justify-content:center">'+chars.map(function(c){return'<div onclick="ElemeModule._cO(\''+fid+'\',\''+c.id+'\')" style="cursor:pointer;text-align:center"><div style="width:50px;height:50px;border-radius:50%;background:rgba(255,255,255,0.2);color:#fff;display:flex;align-items:center;justify-content:center;font-size:1.2rem;font-weight:700;margin:0 auto">'+(c.name||'?')[0]+'</div><div style="color:#fff;font-size:0.65rem;margin-top:4px">'+c.name+'</div></div>'}).join('')+'</div><button onclick="ElemeModule._cPK()" style="margin-top:16px;padding:8px 20px;border-radius:100px;border:1px solid rgba(255,255,255,0.4);background:transparent;color:#fff;cursor:pointer;font-size:0.75rem">取消</button>';pk.style.display='flex'}
  async function _cO(fid,cid){_cPK();var food=_f.find(function(x){return x.id===fid});var ch=await DB.characters.get(Number(cid)).catch(function(){return null});if(!food)return;var pid=PersonaModule.getActiveId();var w=await DB.settings.get('wallet-'+pid).catch(function(){return null});if(!w||w.balance<food.price){_T('余额不足！需'+_fm(food.price)+'，当前'+_fm(w?.balance||0));return}var rm='';try{rm=prompt('外卖备注（可选）：','无接触配送，谢谢！')}catch(e){}w.balance=parseFloat((w.balance-food.price).toFixed(2));w.transactions.unshift({txId:'EM'+Date.now().toString(36),type:'out',descChs:'饿了么 - '+food.name,amount:food.price.toFixed(2),time:new Date().toLocaleString('zh-CN'),status:'SETTLED',channel:'ELEME'});await DB.settings.set('wallet-'+pid,w);_o.unshift({id:_u(),foodName:food.name,restaurant:food.restaurant||'',price:food.price,charId:cid,charName:ch?.name||'角色',remark:rm||'',time:Date.now()});_sO();_rO();if(typeof ConvModule!=='undefined'&&ch){var msg='🥡 我给你点了一份「'+food.name+'」('+_fm(food.price)+') from '+(food.restaurant||'私房小厨')+(rm?'\n备注：'+rm:'')+'\n\n请根据你的人设对此作出回应。';try{await ConvModule.enter(String(cid));var inp=document.getElementById('cv-input');if(inp){inp.value=msg;await ConvModule.sendAndTriggerAI()}}catch(e){}}_T('已为 '+(ch?.name||'角色')+' 点了「'+food.name+'」！')}
  function _cPK(){var p=document.getElementById('em-char-picker');if(p)p.style.display='none'}
  function _oD(fid){var food=_f.find(function(x){return x.id===fid});if(!food)return;document.getElementById('em-detail-content').innerHTML='<div style="text-align:center;padding:10px">'+(food.imageUrl?'<img src="'+food.imageUrl+'" style="width:100%;max-height:250px;object-fit:cover;border-radius:12px">':'<div style="font-size:5rem;padding:30px">🍽</div>')+'</div><h2 style="margin:8px 0 2px">'+food.name+'</h2><p style="font-size:1.3rem;font-weight:800;color:#ff6b35">'+_fm(food.price)+'</p><p style="color:#888;font-size:0.75rem">店铺: '+(food.restaurant||'私房小厨')+'</p><button class="em-order-btn" onclick="ElemeModule._cD();ElemeModule._oFC(\''+fid+'\')">🥡 给 Ta 点单</button>';document.getElementById('em-detail-modal').classList.add('active')}
  function _cD(){document.getElementById('em-detail-modal').classList.remove('active')}
  function _oAC(){document.getElementById('em-add-choice').style.display='flex'}
  function _oE(fid){_e=fid||null;document.getElementById('em-editor-title').textContent=fid?'编辑美食':'添加美食';if(fid){var p=_f.find(function(x){return x.id===fid});if(p){document.getElementById('em-e-name').value=p.name||'';document.getElementById('em-e-price').value=p.price||'';document.getElementById('em-e-img').value=p.imageUrl||'';document.getElementById('em-e-shop').value=p.restaurant||''}}else{['em-e-name','em-e-price','em-e-img','em-e-shop'].forEach(function(id){document.getElementById(id).value=''})}document.getElementById('em-editor-modal').classList.add('active')}
  function _cE(){document.getElementById('em-editor-modal').classList.remove('active');_e=null}
  async function _sF2(){var n=document.getElementById('em-e-name').value.trim(),pr=parseFloat(document.getElementById('em-e-price').value),iu=document.getElementById('em-e-img').value.trim(),re=document.getElementById('em-e-shop').value.trim();if(!n||isNaN(pr)||pr<=0){_T('请填写名称和有效价格');return}if(_e){var p=_f.find(function(x){return x.id===_e});if(p){p.name=n;p.price=pr;p.imageUrl=iu;p.restaurant=re}}else{_f.push({id:_u(),name:n,price:pr,imageUrl:iu,restaurant:re||'私房小厨'})}await _sF();_cE();_r();_T(_e?'已更新':'已添加')}
  async function clearAll(){if(!confirm('确定清空所有美食？'))return;_f=[];await _sF();_r();_T('已清空')}
  async function open(){await _L();document.getElementById('em-overlay').classList.add('active');_r()}
  function close(){document.getElementById('em-overlay').classList.remove('active')}
  function _T(m){if(typeof Toast!=='undefined')Toast.show(m)}
  async function init(){await _L()}
  return{open,close,aiSearch,aiGen,clearAll,init,_oAC,_oE,_cE,_sF2,_oD,_cD,_oFC,_cO,_cPK}
})();
