// TaobaoModule — 桃宝
const TaobaoModule = (() => {
  const KP='taobao-products',KC='taobao-cart',KO='taobao-orders';
  let _p=[],_c=[],_o=[],_e=null,_v='home';
  function _u(){return 'TB'+Date.now().toString(36)+Math.random().toString(36).slice(2,6)}
  function _f(n){return '¥'+Number(n).toFixed(2)}
  async function _L(){try{_p=await DB.settings.get(KP)||[]}catch(e){_p=[]};try{_c=await DB.settings.get(KC)||[]}catch(e){_c=[]};try{_o=await DB.settings.get(KO)||[]}catch(e){_o=[]}}
  async function _sP(){await DB.settings.set(KP,_p)}
  async function _sC(){await DB.settings.set(KC,_c)}
  async function _sO(){await DB.settings.set(KO,_o)}
  function _ct(){return _c.reduce(function(s,i){return s+i.price*(i.qty||1)},0)}
  function _cc(){return _c.reduce(function(s,i){return s+(i.qty||1)},0)}
  async function _AI(prompt,temp){
    let api=null;try{api=await ApiModule.getSecondaryApi()}catch(e){api=await DB.api.getActive().catch(function(){return null})}
    if(!api)return null;
    var fp=prompt;try{var es=await DB.worldInfo.getAll();if(es&&es.length){var fl=es.filter(function(e){return e.scope&&Array.isArray(e.scope)&&e.scope.includes('taobao')});if(fl.length)fp+='\n【世界书参考】'+fl.map(function(e){return e.title+'：'+(e.content||'').slice(0,80)}).join(' | ').slice(0,500)}}catch(e){}
    try{return await ApiHelper.chatCompletion(api,[{role:'user',content:fp}])}catch(e){console.error('[Taobao]',e);return null}
  }
  async function _GI(prompt,pid){var sp=(prompt||'product').slice(0,200);var seed=Math.floor(Math.random()*10000000);var safePos=encodeURIComponent(sp+', product shot, 8k uhd, highres, photorealistic, dslr, aesthetic, studio lighting, clean minimalist, commercial photography, still life, no humans');var safeNeg=encodeURIComponent('human, person, people, man, woman, face, portrait, body, figure, anatomy, nsfw, blurry, watermark, text, signature, logo, label');var url='https://image.pollinations.ai/prompt/'+safePos+'?width=832&height=1216&seed='+seed+'&model=flux-realism&nologo=true&negative_prompt='+safeNeg;var img=document.getElementById('tb-pimg-'+pid);if(img){img.src=url;img.onerror=function(){img.style.display='none';var fb=img.nextElementSibling;if(fb)fb.style.display='flex'};img.onload=async function(){img.style.display='';var fb=img.nextElementSibling;if(fb)fb.style.display='none';var p=_p.find(function(x){return x.id===pid});if(p){p.imageUrl=url;await _sP()}}}}
  async function aiGen(kw){_T('AI正在生成商品...');var prompt=kw?'你是桃宝搜索引擎。根据\"'+kw+'\"创作5-8件商品JSON数组。每件: name, price(数字), category, imagePrompt(英文产品图提示词, clean minimalist)。只返回JSON数组。':'你是桃宝策划师。随机创作5-8件有趣多样的商品JSON数组。每件: name, price(数字), category, imagePrompt(英文产品图提示词, clean minimalist)。只返回JSON数组。';var resp=await _AI(prompt,kw?0.8:1.1);if(!resp){_T('AI调用失败');return}try{var cleaned=resp.replace(/```json|```/g,'').trim();var arr=JSON.parse(cleaned.substring(cleaned.indexOf('['),cleaned.lastIndexOf(']')+1));if(Array.isArray(arr)&&arr.length>0){var items=arr.map(function(p){return{id:_u(),name:p.name,price:Number(p.price)||99,category:p.category||'杂货',imagePrompt:p.imagePrompt||'',imageUrl:'',store:'桃宝AI'}});_p.push.apply(_p,items);await _sP();_rH();_T('生成了'+items.length+'件商品');items.forEach(function(p){if(!p.imageUrl)_GI(p.imagePrompt||p.name,p.id)})}}catch(e){_T('AI返回格式错误')}}
  function _rH(){var g=document.getElementById('tb-product-grid'),cb=document.getElementById('tb-cat-bar');if(!g)return;var cats=[];_p.forEach(function(p){if(p.category&&cats.indexOf(p.category)===-1)cats.push(p.category)});cb.innerHTML=cats.map(function(c){return'<button class="tb-ctag" onclick="TaobaoModule._fC(\''+c.replace(/'/g,"\\'")+'\')">'+c+'</button>'}).join('');if(_p.length===0){g.innerHTML='<div class="tb-empty-state"><p>还没有商品</p><p style="font-size:0.7rem;color:#bbb">点右上角 + 或搜索添加</p></div>';return}g.innerHTML=_p.map(function(p){var ih='<img src="'+(p.imageUrl||'')+'" class="tb-card-img" id="tb-pimg-'+p.id+'" style="'+(p.imageUrl?'':'display:none')+'" onerror="this.style.display=\'none\';this.nextElementSibling.style.display=\'flex\'"><div class="tb-card-emoji-fallback" style="'+(p.imageUrl?'display:none':'display:flex')+'">📦</div>';return'<div class="tb-card"><div class="tb-card-img-wrap" onclick="TaobaoModule._oD(\''+p.id+'\')">'+ih+'</div><div class="tb-card-info" onclick="TaobaoModule._oD(\''+p.id+'\')"><div class="tb-card-name">'+p.name+'</div><div class="tb-card-price">'+_f(p.price)+'</div></div><button class="tb-card-add" onclick="event.stopPropagation();TaobaoModule._aC(\''+p.id+'\')">+</button></div>'}).join('')}
  function _rC(){var el=document.getElementById('tb-cart-list'),ft=document.getElementById('tb-cart-footer');if(!el)return;if(_c.length===0){el.innerHTML='<div class="tb-empty-state">购物车空空如也~</div>';ft.style.display='none'}else{ft.style.display='block';el.innerHTML=_c.map(function(i,idx){return'<div class="tb-cart-row"><span style="font-size:1.8rem">📦</span><div style="flex:1"><b>'+i.name+'</b><br><span style="color:#c0392b;font-weight:800">'+_f(i.price)+'</span></div><div class="tb-cart-qty"><button onclick="TaobaoModule._cQ('+idx+',-1)">-</button><span>'+(i.qty||1)+'</span><button onclick="TaobaoModule._cQ('+idx+',1)">+</button></div><button class="tb-cart-del" onclick="TaobaoModule._rC('+idx+')">×</button></div>'}).join('')}var t=document.getElementById('tb-cart-total'),c=document.getElementById('tb-cart-count');if(t)t.textContent=_f(_ct());if(c)c.textContent=_cc()}
  function _rO(){var el=document.getElementById('tb-orders-list');if(!el)return;if(_o.length===0){el.innerHTML='<div class="tb-empty-state">还没有订单</div>';return}el.innerHTML=_o.map(function(o){return'<div class="tb-order-card"><div style="display:flex;justify-content:space-between"><b>'+(o.items||[]).map(function(i){return i.name}).join(', ')+'</b><span style="color:#c0392b;font-weight:800">'+_f(o.total)+'</span></div><div style="font-size:0.65rem;color:#999;margin:4px 0">'+new Date(o.time).toLocaleString('zh-CN')+' · '+(o.buyer||'自己')+'</div><div style="font-size:0.7rem;color:#1a3a50;font-weight:600">'+(o.status||'已下单')+'</div>'+(o.logistics||[]).map(function(l){return'<div style="font-size:0.6rem;color:#aaa">'+(l.done?'✅':'⏳')+' '+l.text+'</div>'}).join('')+'</div>'}).join('')}
  function _sL(oid){var o=_o.find(function(x){return x.id===oid});if(!o)return;var t=[{t:'订单已提交',d:2000},{t:'仓库已打包',d:15000},{t:'快递已揽收',d:60000},{t:'到达分拨中心',d:300000},{t:'运输中',d:600000},{t:'派送中，快递员：兔兔',d:1800000},{t:'已签收！',d:3600000}];o.logistics=[];o.status='已付款';var cum=0;t.forEach(function(x,i){cum+=x.d;setTimeout(function(){o.logistics.push({text:x.t,time:Date.now(),done:true});if(i===t.length-1)o.status='已签收';else if(i===1)o.status='已发货';else if(i>=3)o.status='运输中';_sO();if(_v==='orders')_rO()},cum)});_sO()}
  async function open(){await _L();document.getElementById('tb-overlay').classList.add('active');_v='home';_sT('home');_rH();_rC();_rO()}
  function close(){document.getElementById('tb-overlay').classList.remove('active')}
  function _sT(v){_v=v;['tb-home-view','tb-cart-view','tb-orders-view'].forEach(function(id){var el=document.getElementById(id);if(el)el.style.display='none'});var el=document.getElementById('tb-'+v+'-view');if(el)el.style.display='flex';document.querySelectorAll('.tb-tab').forEach(function(t,i){t.classList.toggle('on',i===['home','cart','orders'].indexOf(v))});if(v==='orders')_rO()}
  function _fC(cat){} // placeholder
  function _oAC(){var ch=document.getElementById('tb-add-choice');if(ch)ch.style.display='flex'}
  function _oE(pid){_e=pid||null;document.getElementById('tb-editor-title').textContent=pid?'编辑商品':'添加商品';if(pid){var p=_p.find(function(x){return x.id===pid});if(p){document.getElementById('tb-e-name').value=p.name||'';document.getElementById('tb-e-price').value=p.price||'';document.getElementById('tb-e-img').value=p.imageUrl||'';document.getElementById('tb-e-cat').value=p.category||''}}else{['tb-e-name','tb-e-price','tb-e-img','tb-e-cat'].forEach(function(id){document.getElementById(id).value=''})}document.getElementById('tb-editor-modal').classList.add('active')}
  function _cE(){document.getElementById('tb-editor-modal').classList.remove('active');_e=null}
  async function _sP2(){var n=document.getElementById('tb-e-name').value.trim(),pr=parseFloat(document.getElementById('tb-e-price').value),iu=document.getElementById('tb-e-img').value.trim(),ca=document.getElementById('tb-e-cat').value.trim();if(!n||isNaN(pr)||pr<=0){_T('请填写名称和有效价格');return}if(_e){var p=_p.find(function(x){return x.id===_e});if(p){p.name=n;p.price=pr;p.imageUrl=iu;p.category=ca}}else{_p.push({id:_u(),name:n,price:pr,imageUrl:iu,category:ca||'杂货',store:'手动添加'})}await _sP();_cE();_rH();_T(_e?'已更新':'已添加')}
  function _oD(pid){var p=_p.find(function(x){return x.id===pid});if(!p)return;var kw=encodeURIComponent(p.name);document.getElementById('tb-detail-content').innerHTML='<div style="text-align:center;padding:10px">'+(p.imageUrl?'<img src="'+p.imageUrl+'" style="width:100%;max-height:250px;object-fit:cover;border-radius:12px">':'<div style="font-size:5rem;padding:30px">📦</div>')+'</div><h2 style="margin:8px 0 2px">'+p.name+'</h2><p style="font-size:1.4rem;font-weight:800;color:#c0392b">'+_f(p.price)+'</p><p style="color:#888;font-size:0.75rem">店铺: '+(p.store||'桃宝自营')+' | '+(p.category||'')+'</p>'+(p.reviews||[]).map(function(r){return'<div style="background:#fafaf8;border-radius:8px;padding:8px;margin:6px 0;font-size:0.7rem"><b>'+r.author+'</b>: '+r.text+'</div>'}).join('')+'<div style="display:flex;gap:8px;margin-top:12px"><button class="tb-act-btn" onclick="TaobaoModule._aC(\''+pid+'\');TaobaoModule._cD()" style="flex:1;background:#1a3a50;color:#fff">加入购物车</button><button class="tb-act-btn" onclick="TaobaoModule._gR(\''+pid+'\')" style="background:#f0f0f0">✨ 生成评价</button></div><a href="https://s.taobao.com/search?q='+kw+'" target="_blank" style="display:block;text-align:center;margin-top:8px;padding:8px;border-radius:100px;border:1px solid #1a3a50;color:#1a3a50;font-size:0.7rem;text-decoration:none;font-weight:600">📱 去淘宝搜「'+p.name+'」</a>';document.getElementById('tb-detail-modal').classList.add('active')}
  function _cD(){document.getElementById('tb-detail-modal').classList.remove('active')}
  async function _gR(pid){var p=_p.find(function(x){return x.id===pid});if(!p)return;_T('AI正在生成评价...');var prompt='为商品"'+p.name+'"(¥'+p.price+')生成3-5条买家评价JSON数组。每条: author(昵称), text(内容)。只返回JSON数组。';var resp=await _AI(prompt,0.9);if(!resp)return;try{var arr=JSON.parse(resp.replace(/```json|```/g,'').trim());if(Array.isArray(arr)){p.reviews=arr;await _sP();_oD(pid);_T('评价生成成功！')}}catch(e){_T('评价生成失败')}}
  function _aC(pid){var p=_p.find(function(x){return x.id===pid});if(!p)return;var ex=_c.find(function(x){return x.id===pid});if(ex)ex.qty=(ex.qty||1)+1;else _c.push({id:p.id,name:p.name,price:p.price,imageUrl:p.imageUrl,qty:1});_sC();_rC();_T('已加入购物车')}
  function _rCI(idx){_c.splice(idx,1);_sC();_rC()}
  function _cQ(idx,d){_c[idx].qty=(_c[idx].qty||1)+d;if(_c[idx].qty<=0)_c.splice(idx,1);_sC();_rC()}
  async function checkout(){if(_c.length===0){_T('购物车是空的');return}var t=_ct();var pid=PersonaModule.getActiveId();var w=await DB.settings.get('wallet-'+pid).catch(function(){return null});if(!w||w.balance<t){_T('余额不足！需'+_f(t)+'，当前'+_f(w?.balance||0));return}w.balance=parseFloat((w.balance-t).toFixed(2));w.transactions.unshift({txId:'TB'+Date.now().toString(36),type:'out',descChs:'桃宝购物',amount:t.toFixed(2),time:new Date().toLocaleString('zh-CN'),status:'SETTLED',channel:'TAOBAO'});await DB.settings.set('wallet-'+pid,w);var oid=_u();_o.unshift({id:oid,items:_c.map(function(i){return{name:i.name,qty:i.qty}}),total:t,time:Date.now(),status:'已付款',buyer:'自己'});await _sO();_c=[];await _sC();_rC();_rO();_T('购买成功！'+_f(t));_sL(oid)}
  async function sendToChar(){if(_c.length===0){_T('购物车是空的');return}var chars=await DB.characters.getAll().catch(function(){return[]});if(!chars.length){_T('还没有角色');return}var pk=document.getElementById('tb-char-picker');pk.innerHTML='<div style="color:#fff;text-align:center;margin-bottom:12px;font-weight:700">选一个角色帮你清空购物车</div><div style="display:flex;flex-wrap:wrap;gap:10px;justify-content:center">'+chars.map(function(c){return'<div onclick="TaobaoModule._sTC(\''+c.id+'\')" style="cursor:pointer;text-align:center"><div style="width:50px;height:50px;border-radius:50%;background:rgba(255,255,255,0.2);color:#fff;display:flex;align-items:center;justify-content:center;font-size:1.2rem;font-weight:700;margin:0 auto">'+(c.name||'?')[0]+'</div><div style="color:#fff;font-size:0.65rem;margin-top:4px">'+c.name+'</div></div>'}).join('')+'</div><button onclick="TaobaoModule._cPK()" style="margin-top:16px;padding:8px 20px;border-radius:100px;border:1px solid rgba(255,255,255,0.4);background:transparent;color:#fff;cursor:pointer">取消</button>';pk.style.display='flex'}
  async function _sTC(cid){_cPK();var ch=await DB.characters.get(Number(cid)).catch(function(){return null});var t=_ct();var sm=_c.map(function(i){return'📦 '+i.name+' x'+(i.qty||1)+' '+_f(i.price*(i.qty||1))}).join('\n');var msg='🛒 我的购物车（共'+_cc()+'件 '+_f(t)+'）：\n'+sm+'\n\n拜托帮我清空购物车~🙏';_o.unshift({id:_u(),items:_c.map(function(i){return{name:i.name,qty:i.qty}}),total:t,time:Date.now(),status:'等待'+(ch?.name||'角色')+'付款',buyer:ch?.name||'角色',charId:cid});await _sO();_c=[];await _sC();_rC();_rO();if(typeof ConvModule!=='undefined'){try{await ConvModule.enter(String(cid));var inp=document.getElementById('cv-input');if(inp){inp.value=msg;await ConvModule.sendAndTriggerAI()}}catch(e){}}_T('已发送给 '+(ch?.name||'角色'));close()}
  function _cPK(){var p=document.getElementById('tb-char-picker');if(p)p.style.display='none'}
  async function clearAll(){if(!confirm('确定清空所有商品和购物车？'))return;_p=[];_c=[];await _sP();await _sC();_rH();_rC();_T('已清空')}
  function _T(m){if(typeof Toast!=='undefined')Toast.show(m)}
  async function init(){await _L()}
  return{open,close,aiGenerate:aiGen,checkout,sendToChar,clearAll,init,_sT,_fC,_aC,_rCI,_cQ,_oAC,_oE,_cE,_sP2,_oD,_cD,_gR,_sTC,_cPK,_switchTab:_sT,_openAddChoice:_oAC,_openEditor:_oE,_saveProduct:_sP2,_closeEditor:_cE,_closeDetail:_cD,_cancelPicker:_cPK}
})();
